name: 'Documentation Gen'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'edit-3'
  color: 'green'

# Define your inputs here.
inputs:
  source-directory:
    description: 'The path to the directory containing the source code that should be parsed into documentation files.'
    required: true
    default: './'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
